<?xml version="1.0" encoding="utf-8"?><Database Name="ibmjune2023" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.customer" Member="customers">
    <Type Name="customer">
      <Column Name="custid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="custname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="salary" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="phone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>